apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.imageName }}
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 30m
              memory: 96Mi
          ports:
            - containerPort: 80